name: PostgreSQL service example

on: push

jobs:
  container-job:
    name: "job"
    runs-on: ubuntu-latest
    container: node

    services:
      postgres:
        ports:
          - 5432:5432
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - run: npm i
      - run: node sql.js