name: Tests

on: ["push"]


jobs:
  dummy-job:
    name: "Dummy job"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run : npm install
      - run : npm install -g typescript
      - run : npx tsc
      - name: Build and save for later
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifact
          path: dist
  second-job: 
    needs: 
      - dummy-job
    name: "Next Job"
    runs-on: ubuntu-latest
    steps:
      - name: Download previously built files
        uses: actions/download-artifact@v3
        with:
          name: dist-artifact
      - run: "ls -la"