name: Reusable

on:
  workflow_call:

jobs:
  tests:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.2
        with:
          run_install: true
          version: '7.1.7'